//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FJDPXT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class B_ETicket
    {
        public int ETicketID { get; set; }
        public Nullable<int> PNRPassengerID { get; set; }
        public Nullable<int> oderID { get; set; }
        public Nullable<int> flightID { get; set; }
        public Nullable<int> flightCabinID { get; set; }
        public Nullable<int> cabinTypeID { get; set; }
        public string ticketNo { get; set; }
        public Nullable<System.DateTime> tickingTime { get; set; }
        public Nullable<decimal> ticketPrice { get; set; }
        public Nullable<int> payTypeID { get; set; }
        public Nullable<int> operatorID { get; set; }
        public Nullable<System.DateTime> operatingTtime { get; set; }
        public Nullable<int> eTicketStatusID { get; set; }
        public Nullable<int> invoiceStatusID { get; set; }
    }
}
