//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FJDPXT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class B_ETicketChange
    {
        public int ETicketChangeID { get; set; }
        public Nullable<int> oldETicketID { get; set; }
        public Nullable<int> newETicketID { get; set; }
        public Nullable<decimal> addPrice { get; set; }
        public Nullable<int> operatorID { get; set; }
        public Nullable<System.DateTime> operatingTtime { get; set; }
        public Nullable<bool> isVoluntary { get; set; }
        public string changeReason { get; set; }
    }
}
