//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FJDPXT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class B_PNRSegment
    {
        public int PNRSegmentID { get; set; }
        public Nullable<int> PNRID { get; set; }
        public Nullable<int> segmentNo { get; set; }
        public Nullable<int> flightID { get; set; }
        public Nullable<int> cabinTypeID { get; set; }
        public Nullable<int> flightCabinID { get; set; }
        public Nullable<int> bookSeatNum { get; set; }
        public Nullable<int> bookSeatInfo { get; set; }
        public int segmentType { get; set; }
        public bool invalid { get; set; }
    }
}
