//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FJDPXT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class B_PNR
    {
        public int PNRID { get; set; }
        public string PNRNo { get; set; }
        public string contactName { get; set; }
        public string contactPhone { get; set; }
        public string TicketingInfo { get; set; }
        public Nullable<int> PNRStatus { get; set; }
        public Nullable<int> operatorID { get; set; }
        public Nullable<System.DateTime> createTime { get; set; }
    }
}
