//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FJDPXT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class B_PNRTicketing
    {
        public int PNRTicketingID { get; set; }
        public Nullable<int> PNRID { get; set; }
        public Nullable<int> PNRPassengerID { get; set; }
        public Nullable<int> PNRSegmentID { get; set; }
        public Nullable<int> ETicketID { get; set; }
        public Nullable<System.DateTime> TicketingTime { get; set; }
        public Nullable<int> orderID { get; set; }
    }
}
