//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FJDPXT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class B_SpecialTeamApplication
    {
        public int SpecialTeamApplicationID { get; set; }
        public Nullable<int> PNRTeamID { get; set; }
        public string agentApplication { get; set; }
        public Nullable<System.DateTime> applicationTime { get; set; }
        public Nullable<int> agentID { get; set; }
        public string remark { get; set; }
    }
}
