//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FJDPXT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class B_SpecialTeamApproval
    {
        public int SpecialTeamApprovalID { get; set; }
        public Nullable<int> SpecialTeamApplicationID { get; set; }
        public string TourCode { get; set; }
        public Nullable<int> minNum { get; set; }
        public Nullable<int> maxNum { get; set; }
        public Nullable<int> freeNUm { get; set; }
        public string salesPinion { get; set; }
        public string businessPinion { get; set; }
        public string marketingPinion { get; set; }
        public string remark { get; set; }
        public string precautions { get; set; }
        public Nullable<bool> approvalResult { get; set; }
        public Nullable<int> approvalUserID { get; set; }
        public Nullable<System.DateTime> approvalTime { get; set; }
    }
}
