//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FJDPXT.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FJDPXTEntities1 : DbContext
    {
        public FJDPXTEntities1()
            : base("name=FJDPXTEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<B_ETicket> B_ETicket { get; set; }
        public virtual DbSet<B_ETicketChange> B_ETicketChange { get; set; }
        public virtual DbSet<B_ETicketInvalid> B_ETicketInvalid { get; set; }
        public virtual DbSet<B_FlightChange> B_FlightChange { get; set; }
        public virtual DbSet<B_Order> B_Order { get; set; }
        public virtual DbSet<B_PNR> B_PNR { get; set; }
        public virtual DbSet<B_PNROtherInfo> B_PNROtherInfo { get; set; }
        public virtual DbSet<B_PNRPassenger> B_PNRPassenger { get; set; }
        public virtual DbSet<B_PNRSegment> B_PNRSegment { get; set; }
        public virtual DbSet<B_PNRTeam> B_PNRTeam { get; set; }
        public virtual DbSet<B_PNRTicketing> B_PNRTicketing { get; set; }
        public virtual DbSet<B_SpecialTeamApplication> B_SpecialTeamApplication { get; set; }
        public virtual DbSet<B_SpecialTeamApproval> B_SpecialTeamApproval { get; set; }
        public virtual DbSet<B_TicketRefund> B_TicketRefund { get; set; }
        public virtual DbSet<B_TransactionRecord> B_TransactionRecord { get; set; }
        public virtual DbSet<S_Airport> S_Airport { get; set; }
        public virtual DbSet<S_Bulletin> S_Bulletin { get; set; }
        public virtual DbSet<S_CabinType> S_CabinType { get; set; }
        public virtual DbSet<S_CertificatesType> S_CertificatesType { get; set; }
        public virtual DbSet<S_ETicketStatus> S_ETicketStatus { get; set; }
        public virtual DbSet<S_Flight> S_Flight { get; set; }
        public virtual DbSet<S_FlightCabin> S_FlightCabin { get; set; }
        public virtual DbSet<S_FrequentPassenger> S_FrequentPassenger { get; set; }
        public virtual DbSet<S_InvoiceStatus> S_InvoiceStatus { get; set; }
        public virtual DbSet<S_Module> S_Module { get; set; }
        public virtual DbSet<S_PassengerType> S_PassengerType { get; set; }
        public virtual DbSet<S_Permission> S_Permission { get; set; }
        public virtual DbSet<S_PlanType> S_PlanType { get; set; }
        public virtual DbSet<S_Ticket> S_Ticket { get; set; }
        public virtual DbSet<S_User> S_User { get; set; }
        public virtual DbSet<S_UserGroup> S_UserGroup { get; set; }
        public virtual DbSet<S_UserType> S_UserType { get; set; }
        public virtual DbSet<S_VirtualAccount> S_VirtualAccount { get; set; }
    }
}
