//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FJDPXT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class S_CabinType
    {
        public int cabinTypeID { get; set; }
        public string cabinTypeCode { get; set; }
        public string cabinTypeName { get; set; }
        public Nullable<decimal> basisPrice { get; set; }
        public Nullable<decimal> discountRate { get; set; }
    }
}
