//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FJDPXT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class S_Flight
    {
        public int flightID { get; set; }
        public string flightCode { get; set; }
        public Nullable<int> orangeID { get; set; }
        public Nullable<int> destinationID { get; set; }
        public Nullable<System.DateTime> flightDate { get; set; }
        public Nullable<System.TimeSpan> departureTime { get; set; }
        public Nullable<System.TimeSpan> arrivalTime { get; set; }
        public Nullable<int> planTypeID { get; set; }
        public Nullable<decimal> standardPrice { get; set; }
    }
}
